Metrics/AbcSize:
  Max: 20
Metrics/LineLength:
  Max: 88
Metrics/MethodLength:
  Max: 20
Style/AsciiComments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - config/mdl_style.rb
Style/RedundantReturn:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
