Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - spec/*_spec.rb
Metrics/LineLength:
  Max: 88
Metrics/MethodLength:
  Max: 20
Naming/HeredocDelimiterNaming:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - config/mdl_style.rb
Style/RedundantReturn:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
