AllCops:
  NewCops: enable
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Exclude:
    - spec/*_spec.rb
Metrics/MethodLength:
  Max: 20
Naming/HeredocDelimiterNaming:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile
    - config/mdl_style.rb
Style/IfUnlessModifier:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
