# Jekyll settings
timezone: America/New_York

# Theme settings
title: 'Oliver Steele | Code'
email: steele@osteele.com
url: 'https://code.osteele.com' # the base hostname & protocol for your site
github_username: osteele

# Project viewer config
repo_owners: mlsteele

exclude:
  - '*.lock'
  - '*.log'
  - '*.todo'
  - _distr
  - config
  - docker-compose.yml
  - elm-package.json
  - elm-stuff
  - elm.json
  - Gemfile
  - node_modules
  - package.json
  - Procfile
  - README.md
  - scripts
  - src
