# Jekyll settings
timezone: America/New_York

# Theme settings
title: 'Oliver Steele | Code'
email: steele@osteele.com
url: 'https://code.osteele.com'
github_username: osteele

# Project viewer config
github_repos_metadata:
  inherit_from: config/repo_metadata.yml

exclude:
  - '*.lock'
  - '*.log'
  - '*.todo'
  - _site
  - 2017-index.md
  - config
  - docker-compose.yml
  - elm-package.json
  - elm-stuff
  - elm.json
  - Gemfile
  - node_modules
  - package.json
  - Procfile
  - README.md
  - scripts
  - spec
  - src
