# Site settings
title: "Oliver Steele | Code"
email: steele@osteele.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://code.osteele.com" # the base hostname & protocol for your site
timezone: America/New_York
twitter_username: osteele
github_username:  osteele

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highligher: pygments

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
