# Jekyll settings
timezone: America/New_York

# Theme settings
title: "Oliver Steele | Code"
email: steele@osteele.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://code.osteele.com" # the base hostname & protocol for your site
twitter_username: osteele
github_username:  osteele

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

exclude:
  - config
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
