# Jekyll settings
timezone: America/New_York

# Theme settings
title: 'Oliver Steele | Code'
email: steele@osteele.com
url: 'https://code.osteele.com' # the base hostname & protocol for your site
github_username: osteele

exclude:
  - config
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
  - node_modules
