#!/usr/bin/env bash

set -e # halt script on error

bundle exec htmlproofer \
  --allow-hash-href \
  --assume-extension \
  --check-external-hash \
  --check-html \
  --empty-alt-ignore \
  --report-missing-names \
  --report-script-embeds \
  --timeframe 2w \
  --url-ignore "http://localhost:4000/" \
  "$@" \
  ./_site
