#!/usr/bin/env bash

set -e # halt script on error

bundle exec htmlproofer \
  --allow-hash-href \
  --assume-extension \
  --check-external-hash \
  --check-html \
  --empty-alt-ignore \
  --report-missing-names \
  --report-script-embeds \
  --timeframe 2w \
  --url-ignore '/https://glitch.com/edit/#!/cclab-p5js-template/,/https://learn.ml5js.org/#/reference/posenet/' \
  "$@" \
  ./_site
